### âœ… ci_main.yml : CI sur PR vers `main`
name: ğŸš€ Main PR CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'config/packages/reset_password.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: false # or true

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      # Setup PHP, extensions and composer with shivammathur/setup-php
      - name: ğŸ§° Setup PHP, extensions and Composer
        uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
          php-version: 8.2

      # Cache Composer dependencies
      - name: ğŸ—ƒï¸ Cache multiple paths
        uses: actions/cache@v4
        with:
          path: |
            vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      # Install Composer dependencies
      - name: ğŸ“¦ Composer install
        run: |
          composer config --no-plugins allow-plugins.phpstan/extension-installer true
          composer install --no-interaction --no-progress

      # Install Symfony CLI
      - name: ğŸ§­ Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

      # Check vulnerabilities
      - name: ğŸ” Symfony Check Vulnerabilities
        run: symfony check:security

      # Run PHPStan for static analysis
      - name: ğŸ§  PHP Stan
        run: |
          ./vendor/bin/simple-phpunit install
          composer require phpstan/phpstan
          composer require phpstan/extension-installer
          composer require phpstan/phpstan-symfony
          ./vendor/bin/phpstan analyse src --memory-limit 1G

      # Run PHPUnit tests
      - name: âœ… PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist

      # Lint Twig templates
      - name: ğŸ§¾ Twig Template Lint
        run: ./bin/console lint:twig templates --env=prod

      # Lint YAML config
      - name: ğŸ“˜ Lint YAML files
        run: ./bin/console lint:yaml config --parse-tags

      # Lint service container configuration
      - name: ğŸ§ª Lint Parameters and Services
        run: ./bin/console lint:container --no-debug

      # Validate Doctrine entities schema
      - name: ğŸ—„ï¸ Lint Doctrine entities
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
